#!/bin/bash
# Global variables are first defined in 00setup and module
# dependencies are defined in 01import-config-defaults
#
# All overlay/bundle variables (MOD_PARAMS) defaults must go into
# the <module>/module_defaults file.

target=$series
[ -z "$pocket" ] || target=${target}-$pocket
target=${target}:${MOD_PARAMS[__MICROK8S_CHANNEL__]}
MOD_PASSTHROUGH_OPTS+=( --release-name $target )

# Automatically use proxy if in prodstack only
if $(timeout 1s getent hosts squid.internal &> /dev/null) && [ -z "${MOD_PARAMS[__CONTAINERD_PROXY__]}" ]; then
    MOD_MSGS[1_proxy.0]='PROXY: squid.internal exists, setting containerd proxy to http://squid.internal:3128'
    MOD_PARAMS[__CONTAINERD_PROXY__]=http://squid.internal:3128
fi

# Skip processing input if it includes exclusive passthrough options
! has_excl_passthrough_opt && \
while (($# > 0))
do
    case "$1" in
        --containerd-proxy)  #__OPT__type:<str> (default="" unless the hostname squid.internal resolves, then it's http://squid.internal:3128)
            MOD_PARAMS[__CONTAINERD_PROXY__]=$2
            shift
            ;;
        --containerd-no-proxy)  #__OPT__type:<str> (default=127.0.0.1,localhost,::1,10.149.0.0/16,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16)
            MOD_PARAMS[__CONTAINERD_NO_PROXY__]=$2
            shift
            ;;
        --hostpath-storage)  #__OPT__type:<bool> (default=true)
            MOD_PARAMS[__HOSTPATH_STORAGE__]=$2
            shift
            ;;
        *)
            echo "ERROR: invalid input '$1'"
            _usage
            exit 1
            ;;
    esac
    shift
done

MOD_MSGS[microk8s.0]='Use the following commnads to deploy k8s models'
MOD_MSGS[microk8s.1]='juju wait-for application microk8s  --summary'
MOD_MSGS[microk8s.2]='kubeconfig="$(juju exec --unit microk8s/leader -- microk8s config)"'
MOD_MSGS[microk8s.3]='controller="$(juju controller-config controller-name)"'
MOD_MSGS[microk8s.4]='echo "$kubeconfig" | juju add-k8s microk8s --controller "$controller"'
MOD_MSGS[microk8s.5]=''
MOD_MSGS[microk8s.6]='Once destroyed, clean up with:'
MOD_MSGS[microk8s.7]='juju remove-k8s --client --controller $(juju controller-config controller-name) microk8s'
