#!/bin/bash -ex
[[ -z "$NAMESERVER" ]] && export NAMESERVER="10.230.56.2"
[[ -z "$GATEWAY" ]] && export GATEWAY="10.230.56.1"
[[ -z "$CIDR_EXT" ]] && export CIDR_EXT="10.230.56.0/21"
[[ -z "$FIP_RANGE" ]] && export FIP_RANGE="10.230.62.110:10.230.62.129"
[[ -z "$CIDR_PRIV" ]] && export CIDR_PRIV="192.168.21.0/24"
export BARE_METAL=true

./profiles/default $1 $2 $3 $4 $5

